### PR TITLE
unit test writer package

### PR DESCRIPTION
**Pull request by tomekz**
## Description

Added unit tests for `internal/writer` package

## Type of change

- [ ] Bug fix (non-breaking change to fix a bug).
- [ ] Feature (non-breaking change to add functionality).
- [ ] Breaking change.
- [X] Other 

## Issues referenced.

https://github.com/stackql/stackql/issues/280

## Evidence

Screenshot 2023-10-07 at 21 10 00

## Checklist:

- [ ] A full round of testing has been completed, and there are no test failures as a result of these changes.
- [ ] The changes are covered with functional and/or integration robot testing.
- [ ] The changes work on all supported platforms.

### CODE REVIEW

**Comment by general-kroll-4-life** [comment]
Cheers for this.  Running the checks now.  Please do one favour and run `go mod tidy` and then commit and push any changes.

Thanks again

**Comment by tomekz** [comment]
> Cheers for this. Running the checks now. Please do one favour and run `go mod tidy` and then commit and push any changes.
> 
> Thanks again

Done

**Comment by tomekz** [comment]
The "Windows Build" CI job is failing. I sadly can't tell which of the introduced changes caused that

**Comment by general-kroll-4-life** [comment]
> The "Windows Build" CI job is failing. I sadly can't tell which of the introduced changes caused that

@tomekz yes I shall look into it and also it is past time to make the testing failure dumps more useful.  Shall update when i can

**Comment by general-kroll-4-life** [comment]
@tomekz ok finally got into this.  It is some windows specific stuff we have done.  Have got it working and verified as per [this CI action](https://github.com/stackql/stackql/actions/runs/6453133707).  The changes are in [commit `991c14a`](https://github.com/stackql/stackql/commit/991c14a5f94d3e53ef5b001e5b07f410bd4b1c55).  You can either cherry-pick this commit and add push again, or check the PR box to “Allow edits from maintainers”, or do something else I have not thought of; totally up to you 😎

**Comment by tomekz** [comment]
Thanks a lot. I've [applied the fix](https://github.com/stackql/stackql/pull/304/commits/35a362360e201a7a469329773af98c545c2cb68c) for my branch

**Comment by general-kroll-4-life** [comment]
@tomekz  cool cheers.  FYI, presuming this passes, I'm intending to squash and merge.  Much appreciate the good work

**Review by general-kroll-4-life — APPROVED** [review]

**Comment by general-kroll-4-life** [comment]
@tomekz all checks are passed and it is approved.  Please go ahead and `squash and merge` yourself... hopefully we have set things up so that is possible.

**Comment by tomekz** [comment]
Thanks @general-kroll-4-life , I'm glad I could help.  Can I ask you to merge it as I don't have write access to this repo and can't merge it myself

**Pull request merged**
