### PR TITLE
Add unit testing to package `templatenamespace`

### LINKED ISSUE #277: Add unit testing to package `templatenamespace`
Add unit testing for `internal/stackql/templatenamespace `.

Acceptance Criteria:

- 85% unit test coverage.

### PR DESCRIPTION
**Pull request by sanketmp**
## Description

Added unit testing for `internal/stackql/templatenamespace` package

## Type of change

- [ ] Bug fix (non-breaking change to fix a bug).
- [ ] Feature (non-breaking change to add functionality).
- [ ] Breaking change.
- [x] Other (eg: documentation change).

## Issues referenced.
Fixes #277 

## Evidence

EV

## Checklist:

- [ ] A full round of testing has been completed, and there are no test failures as a result of these changes.
- [ ] The changes are covered with functional and/or integration robot testing.
- [ ] The changes work on all supported platforms.
- [x] Unit tests pass locally, as per [the developer guide](/docs/developer_guide.md#unit-tests).
- [ ] Robot tests pass locally, as per [the developer guide](/docs/developer_guide.md#robot-tests).
- [x] Linter passes locally, as per [the developer guide](/docs/developer_guide.md#linting).

### CODE REVIEW

**Comment by sanketmp** [comment]
I am new to golang. Please review.

**Comment by general-kroll-4-life** [comment]
@sanketmp the linting check is failing, all else seems ok.  You can run the linter locally, as per [the developer guide](https://github.com/docs/developer_guide.md#linting).

**Comment by sanketmp** [comment]
> @sanketmp the linting check is failing, all else seems ok. You can run the linter locally, as per [the developer guide](https://github.com/docs/developer_guide.md#linting).

@general-kroll-4-life it's showing me 404 page after clicking the link.
Capture
Seems like the page has been removed from there.

**Comment by general-kroll-4-life** [comment]
@sanketmp sorry here is the correct reference: https://github.com/stackql/stackql/blob/main/docs/developer_guide.md#linting

**Comment by sanketmp** [comment]
Hi @general-kroll-4-life I am getting this error. 
error
But this will violate another rule: var-naming: don't use an underscore in the package name. right??😥

**Comment by general-kroll-4-life** [comment]
Don't expect that applies to test packages. Try it and see

**Comment by sanketmp** [comment]
@general-kroll-4-life I have tried this with an underscore in the package name and it collapses the whole codefile. Also, it does not recognize the `NewTemplateNamespaceConfigurator()` function. My guess is, it's happening for Windows just as this PR https://github.com/stackql/stackql/pull/304/#issuecomment-1751997274 .I could be wrong. 

One more thing. I saw both Lint Workflow runs and neither of them have mentioned this issue/error.

**Comment by general-kroll-4-life** [comment]
@sanketmp  got the tests to work and linter to pass with a couple of changes.  Here below is the output of `git diff HEAD`


```
diff --git a/internal/stackql/templatenamespace/template_namespace_configurator_test.go b/internal/stackql/templatenamespace/template_namespace_configurator_test.go
index 29faefdb..917eda27 100644
--- a/internal/stackql/templatenamespace/template_namespace_configurator_test.go
+++ b/internal/stackql/templatenamespace/template_namespace_configurator_test.go
@@ -1,15 +1,17 @@
-package templatenamespace
+package templatenamespace_test
 
 import (
 	"regexp"
 	"testing"
 	"text/template"
+
+	"github.com/stackql/stackql/internal/stackql/templatenamespace"
 )
 
 func TestGetObjectName(t *testing.T) {
 	regex := regexp.MustCompile(`(?P<objectName>\w+)`)
 	templ := template.Must(template.New("test").Parse("{{.objectName}}"))
-	config, err := NewTemplateNamespaceConfigurator(regex, templ)
+	config, err := templatenamespace.NewTemplateNamespaceConfigurator(regex, templ)
 	if err != nil {
 		t.Fatal(err)
 	}
@@ -35,7 +37,7 @@ func TestGetObjectName(t *testing.T) {
 func TestRenderTemplate(t *testing.T) {
 	regex := regexp.MustCompile(`(?P<objectName>\w+)`)
 	templete := template.Must(template.New("test").Parse("TestRenderTemplate's {{.objectName}}"))
-	config, err := NewTemplateNamespaceConfigurator(regex, templete)
+	config, err := templatenamespace.NewTemplateNamespaceConfigurator(regex, templete)
 	if err != nil {
 		t.Fatal(err)
 	}
@@ -64,7 +66,7 @@ func TestRenderTemplate(t *testing.T) {
 func TestIsAllowed(t *testing.T) {
 	regex := regexp.MustCompile(`(?P<objectName>\w+)`)
 	temp := template.Must(template.New("test").Parse("{{.objectName}}"))
-	conf, e := NewTemplateNamespaceConfigurator(regex, temp)
+	conf, e := templatenamespace.NewTemplateNamespaceConfigurator(regex, temp)
 	if e != nil {
 		t.Fatal(e)
 	}

```


Please let me know if you need anything further?

**Comment by sanketmp** [comment]
Oh right, I hadn't thought of that. Thanks @general-kroll-4-life.
I have updated and committed the changes. 
test passed:
test
lint check passed and gave no errors:
lint

**Review by general-kroll-4-life — APPROVED** [review]
@sanketmp good stuff thank you

**Comment by sanketmp** [comment]
Glad I could help🙌

**Comment by jeffreyaven** [comment]
great job @sanketmp ! can you make sure to give us a ⭐ at https://github.com/stackql/stackql, thanks again!

**Comment by sanketmp** [comment]
⭐Starred. 🎉 Thank you @jeffreyaven it was a great experience.

**Pull request merged**
