### PR TITLE
[294] Add unit testing for package txn_context

### LINKED ISSUE #294: Add unit testing for package `txn_context`
Add unit testing for `internal/stackql/acid/txn_context`.

Acceptance Criteria:

- 85% unit test coverage.

### PR DESCRIPTION
**Pull request by rameshgkwd05**
## Description

We are adding basic unit tests to cover function definitions in package `txn_context`
We are keeping test files under package name `txn_package_test` on the lines on `driver_test` package

NOTE for reviewers: This contribution is for hactoberfest credit please label it so. Thanks!

## Type of change

- [ ] Bug fix (non-breaking change to fix a bug).
- [ ] Feature (non-breaking change to add functionality).
- [ ] Breaking change.
- [x] Other (eg: documentation change).  Unit test coverage

## Issues referenced.
fixes #294 

## Evidence

```go
(base) ➜  txn_context git:(main) pwd              
/Users/i332719/work/git/github.com/stackql/internal/stackql/acid/txn_context
(base) ➜  txn_context git:(main) go test -v -cover
=== RUN   TestNewTransactionContext
--- PASS: TestNewTransactionContext (0.00s)
=== RUN   TestNewTransactionCoordinatorContext
--- PASS: TestNewTransactionCoordinatorContext (0.00s)
PASS
        github.com/stackql/stackql/internal/stackql/acid/txn_context    coverage: 100.0% of statements
ok      github.com/stackql/stackql/internal/stackql/acid/txn_context    0.262s
```
## Checklist:

- [ ] A full round of testing has been completed, and there are no test failures as a result of these changes.
- [ ] The changes are covered with functional and/or integration robot testing.
- [ ] The changes work on all supported platforms.
- [x] Unit tests pass locally, as per [the developer guide](/docs/developer_guide.md#unit-tests).
- [ ] Robot tests pass locally, as per [the developer guide](/docs/developer_guide.md#robot-tests).
- [ ] Linter passes locally, as per [the developer guide](/docs/developer_guide.md#linting).

## Tech Debt

Zero technical debt

### CODE REVIEW

**Comment by rameshgkwd05** [comment]
@jeffreyaven could you review this?

Thanks

**Comment by jeffreyaven** [comment]
Thanks @rameshgkwd05 I'll get @general-kroll-4-life to have a look

**Review by general-kroll-4-life — APPROVED** [review]

**Comment by general-kroll-4-life** [comment]
@rameshgkwd05 thank you kindly

**Comment by rameshgkwd05** [comment]
Thank you @general-kroll-4-life for approving.
Could you lavel it as hactoberfest-accepted so that it can be counted for relevant credit?

**Comment by jeffreyaven** [comment]
done @rameshgkwd05 let me know if this is OK

**Comment by rameshgkwd05** [comment]
> done @rameshgkwd05 let me know if this is OK

thats perfect!
thank you @jeffreyaven

**Pull request merged**
